// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace AlloyDemoKit.Business.Parking
{

    public class ParkingGarage
    {

        [JsonProperty("id")]
        public int Id { get; set; }

        [JsonProperty("lastModifiedDate")]
        public string LastModifiedDate { get; set; }

        [JsonProperty("name")]
        public string Name { get; set; }

        [JsonProperty("description")]
        public string Description { get; set; }

        [JsonProperty("latitude")]
        public double Latitude { get; set; }

        [JsonProperty("longitude")]
        public double Longitude { get; set; }

        [JsonProperty("address")]
        public string Address { get; set; }

        [JsonProperty("contactInfo")]
        public string ContactInfo { get; set; }

        [JsonProperty("city")]
        public City City { get; set; }

        [JsonProperty("parkingServer")]
        public ParkingServer ParkingServer { get; set; }

        [JsonProperty("suggestedFreeThreshold")]
        public int SuggestedFreeThreshold { get; set; }

        [JsonProperty("suggestedFullThreshold")]
        public int SuggestedFullThreshold { get; set; }

        [JsonProperty("capacityRounding")]
        public int CapacityRounding { get; set; }

        [JsonProperty("openingTimes")]
        public OpeningTime[] OpeningTimes { get; set; }

        [JsonProperty("parkingStatus")]
        public ParkingStatus ParkingStatus { get; set; }

        [JsonProperty("blurAvailability")]
        public bool? BlurAvailability { get; set; }

        [JsonProperty("totalCapacity")]
        public int? TotalCapacity { get; set; }
    }

}
