// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace AlloyDemoKit.Business.Parking
{

    public class ParkingStatus
    {

        [JsonProperty("availableCapacity")]
        public int AvailableCapacity { get; set; }

        [JsonProperty("totalCapacity")]
        public int TotalCapacity { get; set; }

        [JsonProperty("open")]
        public bool Open { get; set; }

        [JsonProperty("suggestedCapacity")]
        public string SuggestedCapacity { get; set; }

        [JsonProperty("activeRoute")]
        public string ActiveRoute { get; set; }

        [JsonProperty("lastModifiedDate")]
        public string LastModifiedDate { get; set; }
    }

}
